import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <head></head>
            <body>
                {/* ThemeProvider */}
                <div>
                    <Header />
                    <main id="main" className="relative">
                        {children}
                    </main>
                    <Footer />
                </div>
            </body>
        </html>
    );
}
